# Site settings
title: Prince's Webpage
description: About me
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://princenarula222.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Prince Narula
user_title: AI Developer | Competitive Programmer
email: prince.narula222@gmail.com
twitter_username: narula222
github_username: princenarula222
gplus_username: princenarula222

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
